import { NextResponse } from "next/server";

export async function POST(request) {
    const { type, data } = await request.json();

    if (type === "filing-summary") {
        // Generate a filing summary document
        const { taxSummary, income, expenses, userData } = data;
        
        const lines = [
            `PERSONAL INCOME TAX — FILING SUMMARY`,
            `Generated: ${new Date().toLocaleDateString('en-NG', { dateStyle: 'full' })}`,
            `Taxpayer: ${userData?.name || 'N/A'}`,
            `State: ${userData?.stateOfResidence || 'N/A'}`,
            `TIN: ${userData?.tin || 'To be obtained'}`,
            ``,
            `=== INCOME SUMMARY ===`,
            `Gross Annual Income: ₦${(taxSummary?.grossAnnualIncome || 0).toLocaleString()}`,
            `Number of Sources: ${(income || []).length}`,
            ``,
        ];

        // List income by type
        const byType = {};
        (income || []).forEach(i => {
            byType[i.type] = (byType[i.type] || 0) + (i.amount * (i.exchangeRate || 1));
        });
        Object.entries(byType).forEach(([type, amount]) => {
            lines.push(`  ${type}: ₦${amount.toLocaleString()}`);
        });

        lines.push('');
        lines.push(`=== DEDUCTIONS & RELIEFS ===`);
        lines.push(`Total Deductions: ₦${(taxSummary?.totalDeductions || 0).toLocaleString()}`);
        lines.push(`CRA Applied: ₦${(taxSummary?.craApplied || 0).toLocaleString()}`);
        lines.push(`Pension Relief: ₦${(taxSummary?.pensionRelief || 0).toLocaleString()}`);

        // List expenses by category
        const byCat = {};
        (expenses || []).filter(e => e.isDeductible).forEach(e => {
            byCat[e.category] = (byCat[e.category] || 0) + e.amount;
        });
        if (Object.keys(byCat).length > 0) {
            lines.push('');
            lines.push('Deductible Expenses:');
            Object.entries(byCat).forEach(([cat, amount]) => {
                lines.push(`  ${cat}: ₦${amount.toLocaleString()}`);
            });
        }

        lines.push('');
        lines.push(`=== TAX LIABILITY ===`);
        lines.push(`Taxable Income: ₦${(taxSummary?.taxableIncome || 0).toLocaleString()}`);
        lines.push(`Annual Tax: ₦${(taxSummary?.annualTax || 0).toLocaleString()}`);
        lines.push(`Effective Rate: ${(taxSummary?.effectiveRate || 0).toFixed(2)}%`);
        lines.push(`Monthly Tax: ₦${(taxSummary?.monthlyTax || 0).toLocaleString()}`);
        lines.push('');
        lines.push(`=== NOTES ===`);
        lines.push(`This summary is generated by NairaClare based on data you provided.`);
        lines.push(`It is for informational purposes and should be reviewed by a tax professional.`);
        lines.push(`Filing deadline: March 31, ${new Date().getFullYear()}`);

        const content = lines.join('\n');

        return new NextResponse(content, {
            headers: {
                'Content-Type': 'text/plain; charset=utf-8',
                'Content-Disposition': `attachment; filename="NairaClare_Tax_Filing_Summary_${new Date().getFullYear()}.txt"`,
            },
        });
    }

    if (type === "vat-firs") {
        // Generate VAT report for FIRS
        const { invoices } = data;
        const paidInvoices = (invoices || []).filter(i => i.status === 'paid');
        
        const lines = [
            `VAT REMITTANCE REPORT — FIRS FORMAT`,
            `Generated: ${new Date().toLocaleDateString('en-NG', { dateStyle: 'full' })}`,
            ``,
            `Invoice No | Date | Amount | VAT (7.5%) | WHT`,
        ];

        let totalVat = 0;
        let totalWht = 0;
        paidInvoices.forEach(inv => {
            totalVat += inv.vatAmount || 0;
            totalWht += inv.whtAmount || 0;
            lines.push(`${inv.invoiceNumber} | ${inv.date} | ₦${inv.amount.toLocaleString()} | ₦${(inv.vatAmount || 0).toLocaleString()} | ₦${(inv.whtAmount || 0).toLocaleString()}`);
        });

        lines.push('');
        lines.push(`Total VAT Collected: ₦${totalVat.toLocaleString()}`);
        lines.push(`Total WHT Deducted: ₦${totalWht.toLocaleString()}`);
        lines.push(`Net VAT Remittance: ₦${totalVat.toLocaleString()}`);

        const content = lines.join('\n');
        return new NextResponse(content, {
            headers: {
                'Content-Type': 'text/plain; charset=utf-8',
                'Content-Disposition': `attachment; filename="NairaClare_VAT_FIRS_Report_${new Date().toISOString().slice(0,7)}.txt"`,
            },
        });
    }

    if (type === "invoice") {
        // Generate a simple invoice document
        const { invoice, client } = data;
        const lines = [
            `INVOICE`,
            `Invoice #: ${invoice.invoiceNumber}`,
            `Date: ${invoice.date}`,
            `Due: ${invoice.dueDate}`,
            ``,
            `Bill To: ${client?.name || 'N/A'}`,
            `TIN: ${client?.tin || 'N/A'}`,
            ``,
            `--- Items ---`,
        ];

        let subtotal = 0;
        (invoice.items || []).forEach(item => {
            const lineTotal = item.quantity * item.unitPrice;
            subtotal += lineTotal;
            lines.push(`${item.description} | Qty: ${item.quantity} | ₦${item.unitPrice.toLocaleString()} | ₦${lineTotal.toLocaleString()}`);
        });

        lines.push('');
        lines.push(`Subtotal: ₦${subtotal.toLocaleString()}`);
        lines.push(`VAT (7.5%): ₦${(invoice.vatAmount || 0).toLocaleString()}`);
        lines.push(`WHT (5%): -₦${(invoice.whtAmount || 0).toLocaleString()}`);
        lines.push(`Total: ₦${(subtotal + (invoice.vatAmount || 0)).toLocaleString()}`);
        lines.push('');
        lines.push(`Status: ${invoice.status.toUpperCase()}`);

        const content = lines.join('\n');
        return new NextResponse(content, {
            headers: {
                'Content-Type': 'text/plain; charset=utf-8',
                'Content-Disposition': `attachment; filename="Invoice_${invoice.invoiceNumber}.txt"`,
            },
        });
    }

    return NextResponse.json({ error: "Unknown export type" }, { status: 400 });
}
